# Paths to data .csv files
data_root: ./data
checkpoint_dir: ./checkpoints # where to store and load saved models

# .csv data file names - frequency based data is optional
files:
  train_raw: Synthetic_20-15-80_Train.csv
  test_raw: Synthetic_20-15-20_Test.csv
  train_freq: Synthetic_20-15-80_Train_Freq.csv
  test_freq: Synthetic_20-15-20_Test_Freq.csv

# load model specification
model:
  type: featureless  # featureless, featurebased or stacked
  # Existing model to load
  load_path: ./checkpoints/synthetic_featureless_d5_w300.keras

# Evaluation params - will load defaults if null or invalid
eval:
  batch_size: 4096
  loss: nll          # loss function - mse or nll
